[aliases]
n0=/batmsg { ; Final Fantasy Randomizer Battle Message Writer. IRC Script by Linkshot
n1=  write -a SpellTable.txt Battle Messages
n2=  write -a SpellTable.txt #01: HP up! %ffrspunmsg1
n3=  write -a SpellTable.txt #02: Armor up %ffrspunmsg2
n4=  write -a SpellTable.txt #03: Easy to dodge %ffrspunmsg3
n5=  write -a SpellTable.txt #05: Easy to hit %ffrspunmsg5
n6=  write -a SpellTable.txt #08: %ffrspresmsg1 [Spaces to add: %ffrspreslength $+ ]
n7=  write -a SpellTable.txt #10: Weapons stronger %ffrspunmsg10
n8=  write -a SpellTable.txt #11: Lost intelligence %ffrspunmsg11
n9=  write -a SpellTable.txt #12: %ffrspresmsg2 %ffrspresspill
n10=  write -a SpellTable.txt #13: Attack halted %ffrspunmsg13
n11=  write -a SpellTable.txt #15: Became terrified %ffrspunmsg15
n12=  write -a SpellTable.txt #16: %ffrspresmsg3
n13=  write -a SpellTable.txt #18: Quick shot %ffrspunmsg18
n14=  write -a SpellTable.txt #21: Erased %ffrspunmsg21
n15=  write -a SpellTable.txt #22: Fell into crack %ffrspunmsg22
n16=  write -a SpellTable.txt #24: HP max! %ffrspunmsg24
n17=  write -a SpellTable.txt #25: %ffrspresmsg4
n18=  write -a SpellTable.txt #27: Weapon became enchanted %ffrspunmsg27
n19=  write -a SpellTable.txt #28: %ffrspresmsg5
n20=  write -a SpellTable.txt #29: Defenseless %ffrspunmsg29
n21=  write -a SpellTable.txt #30: Time stopped %ffrspunmsg30
n22=  write -a SpellTable.txt #31: Exile to 4th dimension %ffrspunmsg31
n23=  write -a SpellTable.txt #43: Critical hit!! %ffrspunmsg43
n24=  write -a SpellTable.txt #47: Stopped %ffrspunmsg47
n25=  write -a SpellTable.txt #74: Ineffective now %ffrspunmsg74
n26=  write -a SpellTable.txt #76: %ffrspmsg76
n27=  write -a SpellTable.txt #77: Poison smoke %ffrspunmsg77
n28=}
